#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$app = new Symfony\Component\Console\Application('ISBN & ISSN list generator for the SFX Dataloader.', '1.0');
$app->add(new Dataloader\IsbnCommand);

$app->run();
