#! /usr/bin/env php

<?php

use Dataloader\ConvertIsbnCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('ISBN & ISSN list generator for the SFX Dataloader.', '1.0');

$app->add(new ConvertIsbnCommand);

$app->run();