#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('ISBN & ISSN list generator for the SFX Dataloader.', '0.1.2');
$app->add(new Dataloader\IsbnCommand);
$app->add(new Dataloader\IssnCommand);

$app->run();
